services:

  # Sistema Unificado (Backend Node.js servindo Frontend Vite/React)
  - type: web
    name: apgb-system-api
    env: node
    plan: free
    buildCommand: npm install --prefix frontend --include=dev && npm run build --prefix frontend && npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
